### ISSUE TITLE
Fails with nvsize!=8

### ISSUE THREAD

**Issue by andk** [eokoe/Net-Flotum#5]
As per subject. Sample fail report: 

http://www.cpantesters.org/cpan/report/72184844

Nvsize varies with the parameter -Duselongdouble. See how the test results correlate: 

http://analysis.cpantesters.org/reports_by_field?distv=Net-Flotum-0.09;field=conf%3Anvsize

In the diagnostics I cannot recognize what the exact reason is but since we have already >15 fails with nvsize=16 and none with 8, it's quite likely that there is some floating point math involved.

HTH&&Thanks,

**Comment by renatocron** [comment]
The most odd part is, the only failing test is https://github.com/eokoe/Net-Flotum/blob/master/t/02-load-by-remote-id.t 

But it only call API and do something with network like all others do.

I will release a new version without it to test if is something related with it.

Thanks for your time
